/**
 * models/Payment.js — Mongoose Model for Payment Transactions
 *
 * Each Payment document records a single financial transaction linked to one
 * Booking. When a user completes checkout, the paymentController creates a
 * Payment document and, on success, flips the linked Booking's isPaid flag.
 *
 * Schema fields:
 *  user          — The User who made the payment
 *  booking       — The Booking this payment is for (one-to-one in practice)
 *  amount        — Exact amount charged in the listed currency
 *  currency      — ISO 4217 code; defaults to 'LKR' (Sri Lankan Rupee)
 *  method        — Payment method used (currently always 'card')
 *  status        — Lifecycle: 'pending' → 'success' / 'failed' / 'refunded'
 *  transactionId — Auto-generated unique reference (TXN-<timestamp>-<random>)
 *  cardLast4     — Last 4 digits of the card used (for receipt display only)
 *  cardBrand     — Card network name (e.g. 'Visa', 'Mastercard') for the receipt
 *  paidAt        — Timestamp set when status transitions to 'success'
 *  timestamps    — Mongoose adds createdAt and updatedAt
 *
 * Pre-save middleware:
 *  Generates a unique transactionId (TXN-<ms>-<random4>) if not already set.
 *  This mirrors the Booking model's bookingRef auto-generation pattern.
 *
 * Business rule:
 *  After a successful payment, paymentController sets booking.isPaid = true,
 *  which unlocks PDF export and Google Maps route generation for the user.
 */

const mongoose = require('mongoose');

// ── Payment Schema Definition ─────────────────────────────────────────────────
const paymentSchema = new mongoose.Schema({
  // The authenticated user who initiated this payment
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

  // The booking that this payment settles — booking.isPaid is set true on success
  booking: { type: mongoose.Schema.Types.ObjectId, ref: 'Booking', required: true },

  // Total amount charged — should equal booking.totalAmount (validated server-side)
  amount: { type: Number, required: true },

  // Currency of the transaction; the platform operates in LKR by default
  currency: { type: String, default: 'LKR' },

  // Payment method identifier — 'card' is the only supported method in this version
  method: { type: String, default: 'card' },

  // Transaction lifecycle state:
  //  'pending'  — Payment initiated but not yet confirmed by the payment gateway
  //  'success'  — Payment confirmed; booking.isPaid will be set to true
  //  'failed'   — Payment was declined or encountered an error
  //  'refunded' — A previously successful payment has been reversed
  status: { type: String, enum: ['pending', 'success', 'failed', 'refunded'], default: 'pending' },

  // Unique transaction identifier — auto-generated by the pre-save hook below
  // Format: TXN-<milliseconds>-<random 0-9998>
  transactionId: { type: String, unique: true },

  // Last 4 digits of the card used — stored for receipt and support purposes only
  // Never store full card numbers (PCI DSS compliance)
  cardLast4: { type: String, default: '' },

  // Card network label (e.g. 'Visa', 'Mastercard') shown on the booking confirmation screen
  cardBrand: { type: String, default: '' },

  // Timestamp recording exactly when payment status became 'success'
  // Set explicitly in paymentController when processing a successful transaction
  paidAt: { type: Date },
}, { timestamps: true }); // Mongoose adds createdAt and updatedAt automatically

// ── Pre-save: Auto-generate Transaction ID ────────────────────────────────────
// Runs before every save but only assigns a transactionId on the first save,
// when the field has not yet been set. The TXN prefix distinguishes payment
// references from booking references (DS- prefix) in support queries.
paymentSchema.pre('save', function (next) {
  if (!this.transactionId) {
    // Combine millisecond timestamp with a 4-digit random number for uniqueness
    this.transactionId = 'TXN-' + Date.now() + '-' + Math.floor(Math.random() * 9999);
  }
  next();
});

// Export the compiled Mongoose model used by paymentController
module.exports = mongoose.model('Payment', paymentSchema);
