/**
 * utils/pdfExport.js — PDF Booking Confirmation & Itinerary Export
 *
 * Generates a professionally formatted A4 PDF document using jsPDF.
 * Called from BookingDetailPage when the user clicks "Download PDF".
 * The PDF is locked behind the payment gate — only bookings with isPaid = true
 * expose the download button in the UI.
 *
 * Function: exportPlanToPDF(plan, booking?)
 *
 * Parameters:
 *  plan    {object} — The itinerary/package/cart shape:
 *                     { name, places[], estimatedTotalCost, planDate,
 *                       estimatedDuration, description }
 *  booking {object} — Optional booking record. When provided, a full
 *                     "Booking Confirmation" section is prepended to the PDF
 *                     including: bookingRef, visitDate, bookingType, passengers,
 *                     payment status, amount, notes, and cart order summary.
 *
 * PDF structure:
 *  1. Header band    — Dark green background, gold DayScape logo, subtitle, reference line
 *  2. Gold accent bar — Visual separator below the header
 *  3. Booking section — (only when booking is provided) confirmation details table
 *  4. Plan name + meta — Trip name, date, duration, cost if no booking
 *  5. Itinerary       — Numbered stops with visit time, duration, distance, entry price, notes
 *  6. Trip summary    — Stop count, passengers, total paid, booking reference
 *  7. Footer          — "Generated by DayScape on <date> | Page N of N" on every page
 *
 * Reference location shown in header and summary:
 *  38, Rajasinghe Road, Dehiwala, Colombo — Lat: 6.868671, Lng: 79.860689
 *
 * Filename format: DayScape-<plan-name-slug>.pdf
 */

import { jsPDF } from 'jspdf';

/**
 * DayScape PDF Export
 * @param {object} plan   - plan/package/cart shape: { name, places, estimatedTotalCost, planDate, estimatedDuration, description }
 * @param {object} [booking] - optional booking record for full confirmation details
 */
export function exportPlanToPDF(plan, booking = null) {
  // Initialise an A4 portrait document in millimetres
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210; // A4 page width in mm
  const M = 20;  // Left/right margin in mm

  // ── Header background (dark green) ──────────────────────────
  // Solid dark-green rectangle across the full page width
  doc.setFillColor(22, 63, 47);
  doc.rect(0, 0, W, 46, 'F');

  // Gold accent bar — thin separator below the main header band
  doc.setFillColor(201, 168, 76);
  doc.rect(0, 42, W, 4, 'F');

  // App name in gold bold — "DayScape"
  doc.setTextColor(201, 168, 76);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.text('DayScape', M, 20);

  // White subtitle describing the platform
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text('Local Tourist Day-Visit Planner - Colombo, Sri Lanka', M, 30);

  // Small reference line with GPS coordinates and website
  doc.setFontSize(8.5);
  doc.setTextColor(180, 210, 195);
  doc.text('38, Rajasinghe Road, Dehiwala, Colombo  |  Lat: 6.868671  Lng: 79.860689  |  dayscape.lk', M, 38);

  let y = 58; // Current vertical cursor position (advances as content is added)

  // ── Booking Confirmation section ─────────────────────────────
  // Only rendered when a booking object is provided (i.e. from BookingDetailPage)
  if (booking) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(20, 20, 20);
    doc.text('Booking Confirmation', M, y);
    y += 7;

    // Highlighted reference number box with gold border
    doc.setFillColor(245, 243, 235);
    doc.setDrawColor(201, 168, 76);
    doc.setLineWidth(0.5);
    doc.roundedRect(M, y, W - M * 2, 10, 1.5, 1.5, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(120, 90, 20);
    doc.text('Booking Reference', M + 4, y + 4);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(160, 120, 20);
    doc.text(booking.bookingRef || '-', W - M - 4, y + 4, { align: 'right' });
    y += 14;

    // Build the booking detail rows array
    const bookingDetails = [];

    if (booking.visitDate) {
      try {
        const d = new Date(booking.visitDate);
        bookingDetails.push(['Visit Date', d.toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })]);
      } catch (e) {}
    }

    // Human-readable label for the booking type discriminator
    const typeLabel = booking.bookingType === 'plan' ? 'Day Plan' : booking.bookingType === 'cart' ? 'Cart Booking' : 'Package';
    bookingDetails.push(['Booking Type', typeLabel]);

    // Passengers row — combines adult and child count
    const adults = booking.adults ?? null;
    const children = booking.children ?? 0;
    if (adults !== null) {
      let guestStr = `${adults} Adult${adults !== 1 ? 's' : ''}`;
      if (children > 0) guestStr += `, ${children} Child${children !== 1 ? 'ren' : ''}`;
      const total = adults + children;
      guestStr += `  (${total} Passenger${total !== 1 ? 's' : ''} total)`;
      bookingDetails.push(['Passengers', guestStr]);
    }

    bookingDetails.push(['Payment Status', booking.isPaid ? 'PAID' : 'PAID']);
    bookingDetails.push(['Amount Paid', `LKR ${(booking.totalAmount || 0).toLocaleString()}`]);

    if (booking.createdAt || booking.bookingDate) {
      try {
        const bd = new Date(booking.createdAt || booking.bookingDate);
        bookingDetails.push(['Booked On', bd.toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })]);
      } catch (e) {}
    }

    // Render each booking detail as an alternating-row table
    bookingDetails.forEach(([label, value], i) => {
      const isLast      = i === bookingDetails.length - 1;
      const isAmountRow = label === 'Amount Paid';
      const isPaidRow   = label === 'Payment Status';

      // Alternating row background (very subtle off-white vs pure white)
      doc.setFillColor(i % 2 === 0 ? 250 : 255, i % 2 === 0 ? 250 : 255, i % 2 === 0 ? 248 : 255);
      doc.rect(M, y, W - M * 2, 7, 'F');

      // Label in grey
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 100, 100);
      doc.text(label, M + 3, y + 4.8);

      // Value — bold and coloured for the amount and payment status rows
      doc.setFont('helvetica', isAmountRow ? 'bold' : 'normal');
      doc.setFontSize(isAmountRow ? 9.5 : 8.5);
      if (isPaidRow && value === 'PAID') {
        doc.setTextColor(22, 140, 90);  // Green for PAID status
      } else if (isAmountRow) {
        doc.setTextColor(160, 120, 20); // Gold for the amount
      } else {
        doc.setTextColor(30, 30, 30);
      }
      doc.text(value, W - M - 3, y + 4.8, { align: 'right' });

      // Thin divider between rows (except after the last row)
      if (!isLast) {
        doc.setDrawColor(220, 220, 215);
        doc.setLineWidth(0.2);
        doc.line(M, y + 7, W - M, y + 7);
      }
      y += 7;
    });

    // Special requests / notes from the booking (if any)
    if (booking.notes) {
      y += 3;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(110, 90, 40);
      doc.text('Special Requests:', M, y);
      y += 4.5;
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8.5);
      doc.setTextColor(90, 90, 90);
      const noteLines = doc.splitTextToSize(booking.notes, W - M * 2);
      doc.text(noteLines, M, y);
      y += noteLines.length * 4.5 + 2;
    }

    // Cart order summary — line items listed for cart bookings
    if (booking.bookingType === 'cart' && booking.cartItems?.length > 0) {
      y += 4;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(20, 20, 20);
      doc.text('Order Summary', M, y);
      y += 6;

      booking.cartItems.forEach((ci, i) => {
        // Page overflow guard — add a new page if content exceeds safe area
        if (y > 265) { doc.addPage(); y = 20; }

        const itemName     = ci.name || ci.package?.name || ci.plan?.name || 'Item';
        const itemAdults   = ci.adults ?? 0;
        const itemChildren = ci.children ?? 0;
        const itemPrice    = ci.price ?? 0;
        // Children charged at 50% of adult price
        const itemTotal    = Math.round(itemPrice * (itemAdults + itemChildren * 0.5));

        // Alternating row background for the order items
        doc.setFillColor(i % 2 === 0 ? 248 : 255, i % 2 === 0 ? 248 : 255, i % 2 === 0 ? 245 : 255);
        doc.rect(M, y, W - M * 2, 12, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(20, 20, 20);
        doc.text(itemName, M + 3, y + 4.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        let guestLine = `${itemAdults} adult${itemAdults !== 1 ? 's' : ''}`;
        if (itemChildren > 0) guestLine += `, ${itemChildren} child${itemChildren !== 1 ? 'ren' : ''}`;
        if (itemPrice > 0) guestLine += `  |  LKR ${itemPrice.toLocaleString()} / adult`;
        doc.text(guestLine, M + 3, y + 9);

        // Per-item total in gold on the right
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9.5);
        doc.setTextColor(160, 120, 20);
        doc.text(`LKR ${itemTotal.toLocaleString()}`, W - M - 3, y + 7, { align: 'right' });

        doc.setDrawColor(220, 220, 215);
        doc.setLineWidth(0.2);
        doc.line(M, y + 12, W - M, y + 12);
        y += 12;
      });

      // Cart grand total row
      y += 1;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(50, 50, 50);
      doc.text('Total', M + 3, y + 4.5);
      doc.setTextColor(160, 120, 20);
      doc.text(`LKR ${(booking.totalAmount || 0).toLocaleString()}`, W - M - 3, y + 4.5, { align: 'right' });
      y += 10;
    }

    // Gold divider separating the booking section from the itinerary
    y += 4;
    doc.setDrawColor(201, 168, 76);
    doc.setLineWidth(0.6);
    doc.line(M, y, W - M, y);
    y += 10;
  }

  // ── Plan / package name ──────────────────────────────────────
  doc.setTextColor(15, 15, 15);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text(plan.name || 'My Day Plan', M, y);
  y += 9;

  // Meta row (date / duration / cost) — only shown when no booking is provided
  // When a booking IS present, this info is already in the booking confirmation table
  if (!booking) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    const metaParts = [];
    if (plan.planDate) {
      try {
        const d = new Date(plan.planDate);
        metaParts.push('Date: ' + d.toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }));
      } catch (e) {}
    }
    if (plan.estimatedDuration)  metaParts.push('Duration: ' + plan.estimatedDuration);
    if (plan.estimatedTotalCost) metaParts.push('Est. Cost: LKR ' + plan.estimatedTotalCost.toLocaleString());
    if (metaParts.length) {
      doc.text(metaParts.join('   |   '), M, y);
      y += 6;
    }
  }

  // Optional plan description paragraph
  if (plan.description) {
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    const lines = doc.splitTextToSize(plan.description, W - M * 2);
    doc.text(lines, M, y);
    y += lines.length * 4.5 + 2;
  }

  // Gold divider before the itinerary (only when no booking header is present)
  if (!booking) {
    doc.setDrawColor(201, 168, 76);
    doc.setLineWidth(0.6);
    doc.line(M, y, W - M, y);
    y += 10;
  }

  // ── Itinerary section title ──────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text('Itinerary', M, y);
  y += 10;

  // ── Stops ────────────────────────────────────────────────────
  // Render each plan stop as a numbered bullet with place details below
  const places = plan.places || [];

  if (places.length === 0) {
    // Empty plan fallback message
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(140, 140, 140);
    doc.text('No stops added to this plan.', M, y);
    y += 8;
  } else {
    places.forEach((item, idx) => {
      // Page overflow guard — add a new page before printing near the bottom
      if (y > 262) {
        doc.addPage();
        y = 20;
      }

      const p      = item.place || {};
      const name   = typeof p === 'object' ? (p.name || 'Place') : 'Place';
      const dist   = typeof p === 'object' ? p.distanceFromReference : null;
      const entry  = typeof p === 'object' ? p.entryType : null;
      const ticket = typeof p === 'object' ? p.tickets?.localAdult : null;

      // Numbered gold circle bullet
      doc.setFillColor(201, 168, 76);
      doc.circle(M + 4.5, y - 1.5, 4.5, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      // Adjust x offset for single vs double digit numbers
      doc.text(String(idx + 1), M + (idx < 9 ? 3.5 : 2.5), y + 1);

      // Place name in large bold text
      doc.setTextColor(15, 15, 15);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.text(name, M + 13, y);
      y += 6;

      // Meta row: time, duration, distance, entry price
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(90, 90, 90);
      const mp = [];
      if (item.visitTime) mp.push('Time: ' + item.visitTime);
      if (item.duration)  mp.push('Duration: ' + item.duration);
      if (dist)           mp.push('Distance: ' + dist + ' km from ref.');
      if (entry === 'free')  mp.push('Entry: Free');
      else if (ticket)       mp.push('Entry: LKR ' + ticket + ' (local adult)');
      if (mp.length) {
        doc.text(mp.join('   ·   '), M + 13, y);
        y += 5;
      }

      // Optional stop-specific notes in italic
      if (item.notes) {
        doc.setTextColor(110, 90, 40);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        const noteLines = doc.splitTextToSize('Note: ' + item.notes, W - M * 2 - 13);
        doc.text(noteLines, M + 13, y);
        y += noteLines.length * 4;
        doc.setFont('helvetica', 'normal');
      }

      // Downward arrow connector between stops (not after the last stop)
      if (idx < places.length - 1) {
        doc.setTextColor(180, 180, 180);
        doc.setFontSize(11);
        doc.text('v', M + 4.5, y + 4);
        y += 9;
      } else {
        y += 4;
      }
    });
  }

  // ── Trip summary box ─────────────────────────────────────────
  // Only rendered if there is enough space remaining on the page
  if (y < 240) {
    y += 6;
    doc.setDrawColor(220, 220, 210);
    doc.setLineWidth(0.4);
    doc.line(M, y, W - M, y);
    y += 7;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(25, 25, 25);
    doc.text('Trip Summary', M, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(70, 70, 70);

    const summary = ['Total Stops: ' + places.length];

    if (booking) {
      // Summary includes booking-specific data when booking object is present
      const adults   = booking.adults ?? null;
      const children = booking.children ?? 0;
      if (adults !== null) {
        let ps = `${adults} Adult${adults !== 1 ? 's' : ''}`;
        if (children > 0) ps += `, ${children} Child${children !== 1 ? 'ren' : ''}`;
        summary.push('Passengers: ' + ps);
      }
      if (booking.visitDate) {
        try {
          summary.push('Visit Date: ' + new Date(booking.visitDate).toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }));
        } catch (e) {}
      }
      summary.push('Amount Paid: LKR ' + (booking.totalAmount || 0).toLocaleString());
      summary.push('Payment Status: ' + (booking.isPaid ? 'PAID' : 'Pending'));
      summary.push('Booking Reference: ' + (booking.bookingRef || '-'));
    } else {
      // Summary shows plan estimates when no booking is provided
      if (plan.estimatedDuration)  summary.push('Estimated Duration: ' + plan.estimatedDuration);
      if (plan.estimatedTotalCost) summary.push('Estimated Cost (local adult): LKR ' + plan.estimatedTotalCost.toLocaleString());
    }

    // Always include the reference location for the traveller's navigation context
    summary.push('Reference: 38 Rajasinghe Road, Dehiwala, Colombo (Lat: 6.868671, Lng: 79.860689)');

    summary.forEach(s => { doc.text(s, M, y); y += 5; });
  }

  // ── Footer — printed on every page ──────────────────────────
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(160, 160, 160);
    const now = new Date().toLocaleString('en-GB');
    // Left: generation timestamp and page number
    doc.text('Generated by DayScape on ' + now + '   |   Page ' + i + ' of ' + pages, M, 291);
    // Right: platform branding
    doc.text('DayScape - Local Tourist Day-Visit Planner | Colombo, Sri Lanka', W - M, 291, { align: 'right' });
  }

  // Build a safe filename from the plan name and trigger the browser download
  const filename = 'DayScape-' + (plan.name || 'itinerary').replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-') + '.pdf';
  doc.save(filename);
}
